{
    "test_case": "index.create_project",
    "result": "fail",
    "steps": [
        "error__5f40e3b3"
    ],
    "description": "Verify that the user can create a new project in the index page",
    "error": "Traceback (most recent call last):\n  File \"/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py\", line 77, in run_test\n    test_module.setup(golem.core.test_data)\n  File \"/Users/lucianofeo/Desktop/golem/src/examples/projects/golem/tests/index/create_project.py\", line 8, in setup\n    go_to('http://localhost:8000/')\n  File \"/Users/lucianofeo/Desktop/golem/src/golem/core/actions.py\", line 113, in go_to\n    driver.get(url)\n  File \"/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 269, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 257, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.WebDriverException: Message: Error loading page\n\n",
    "short_error": "\n",
    "test_elapsed_time": 5.97,
    "test_timestamp": "2017.07.31.23.35.08.244",
    "browser": "firefox"
}