{
    "test_case": "login.login_missing_username",
    "result": "fail",
    "steps": [
        "error__f9c70f8a"
    ],
    "description": "Verify that the user cannot log in if username value is missing",
    "error": "Traceback (most recent call last):\n  File \"/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py\", line 82, in run_test\n    test_module.test(golem.core.test_data)\n  File \"/Users/lucianofeo/Desktop/golem/src/examples/projects/golem/tests/login/login_missing_username.py\", line 10, in test\n    go_to('http://localhost:8000/')\n  File \"/Users/lucianofeo/Desktop/golem/src/golem/core/actions.py\", line 113, in go_to\n    driver.get(url)\n  File \"/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 269, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 257, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.WebDriverException: Message: Error loading page\n\n",
    "short_error": "\n",
    "test_elapsed_time": 7.36,
    "test_timestamp": "2017.07.31.23.35.14.223",
    "browser": "firefox"
}